@startuml

class Material {
    + id: Int
    + nombre: String
    + cantidad: Int
    + tipoMaterial: String
    + espesor: Float
    - actualizar_materiales(): void
    -consultar_cantidad(): void
}

class Chapa{
    + largo: Float
    + tipoChapa: String
}
class CañoCuadrado{
    + lado_1 : Int
    + lado_2 : Int
}
class CañoRedondo{
    + diametro: Float
}
class Hierro{
    + diametro: Float
}
class Angulo{
    + ala: Float
}
class Planchuela{
    + tipo : String
    + ancho: Float
}
class Perfil{
    + alto: Int
}

class Plegados {
    + tamaño: Float
}

class Persona{
    + nombre: String
    + apellido: String
    + localidad: String
    + celular: String
    + direccion : String
}

class Entrega {
    + id: Int
    + fecha: Date
    + materiales: List<Material>
}

class Cliente{
    + id: Int
    + trabajos: List<Trabajo>
    + pagos: List<Pago>
    + entregas: List<Entrega>
}

class Proveedor {
    + id: Int 
    + email: String
    - modificar_informacion(): void
}

class Trabajo {
    + id: Int
    + nombre: String
    + descripcion_trabajo: String
    + precio: Float
    + estado_trabajo: String
    + fecha_ingreso: Date
    + fecha_entrega: Date
    + materiales: List<Material>
    - modificar_trabajos(): void
    - actualizar_precio(nuevoPrecio:Float): void
}

class Pago{
    + id: Int
    + descripcion: String
    + fecha: Date
    + estado: String
    + importe: Float
}

class Transferencia{
    + cbu : String
    + banco : String
    + titularCuenta : String
}

class Efectivo{
}

class Sistema {
    + proveedores: List<Proveedor>
    + materiales: List<Material>
    + entregas: List<Entrega>
    + clientes: List<Cliente>

    + agregar_cliente(cliente:Cliente): void
    + consultar_clientes(): void

    - agregar_trabajo(trabajo:Trabajo): void
    + consultar_trabajos(): void
    - asociar_trabajo(trabajo:Trabajo,cliente:Cliente): void
    
    + registrar_pago(pago:Pago): void
    
    + asociar_pago(cliente:Cliente,pago:Pago): void

    + registrar_proveedor(proveedor:Proveedor): void
    + consultar_proveedores(): void

    + registrar_material(material:Material): void
    + consultar_materiales(): void
    + asociar_material(trabajo:Trabajo,material:Material): void

    + registrar_entrega(entrega:Entrega, proveedor:Proveedor): void
    + asociar_entrega(cliente:Cliente,entrega:Entrega): void
    + consultar_entrega(): void
}

Persona <|-- Cliente
Persona <|-- Proveedor

Material <|-- Plegados
Material <|-- CañoRedondo
Material <|-- CañoCuadrado
Material <|-- Chapa
Material <|-- Hierro
Material <|-- Angulo
Material <|-- Planchuela
Material <|-- Perfil

Material "0..*" -- "0..1" Proveedor : es provisto

Cliente "1" --O "0..*" Trabajo : tiene
Trabajo "1" o-- "0..*" Material : utiliza

Cliente "1" -- "0..*" Entrega : recibe
Proveedor "1" -- "0..*" Entrega : entrega
Entrega "1" -- "0..*" Material : contiene

Pago <|-- Efectivo
Pago <|-- Transferencia

Cliente "1" -- "0..*" Pago : realiza
Sistema o-- Cliente

@enduml
