@startuml


class Material {
    + id: Int
    + nombre: String
    + cantidad: Int
    + tipo_material: String
    + espesor: Float

    + actualizar_cantidad(nuevaCantidad: Int): void
    + consultar_cantidad(): Int
}

class Chapa {
    + largo: Float
    + tipo_chapa: String
}
class CañoCuadrado {
    + lado_1: Int
    + lado_2: Int
}
class CañoRedondo {
    + diametro: Float
}
class Hierro {
    + diametro: Float
}
class Angulo {
    + ala: Float
}
class Planchuela {
    + tipo: String
    + ancho: Float
}
class Perfil {
    + alto: Int
}
class Plegados {
    + tamaño: Float
}

class Persona {
    + nombre: String
    + apellido: String
    + localidad: String
    + celular: String
    + direccion: String
}

class Cliente {
    + id: Int
    + trabajos: List<Trabajo>
    + pagos: List<Pago>
    + entregas: List<Entrega>

    + agregar_trabajo(trabajo:Trabajo): void
    + registrar_pago(pago:Pago): void
    + recibir_entrega(entrega:Entrega): void
    + consultar_trabajos(): List<Trabajo>
    + consultar_pagos(): List<Pago>
    + consultar_entregas(): List<Entrega>
}

class Proveedor {
    + id: Int 
    + email: String

    + modificar_informacion(emailNuevo:String): void
    + registrar_entrega(entrega:Entrega): void
}

class Entrega {
    + id: Int
    + fecha: Date
    + materiales: List<Material>

    + agregar_material(material:Material): void
    + consultar_materiales(): List<Material>
}

class Trabajo {
    + id: Int
    + nombre: String
    + descripcion_trabajo: String
    + precio: Float
    + estado_trabajo: String
    + fecha_ingreso: Date
    + fecha_entrega: Date
    + materiales: List<Material>

    + modificar_trabajo(nuevoEstado:String): void
    + actualizar_precio(nuevoPrecio:Float): void
    + agregar_material(material:Material): void
    + consultar_materiales(): List<Material>
}

class Pago {
    + id: Int
    + descripcion: String
    + fecha: Date
    + estado: String
    + importe: Float
}

class Transferencia {
    + cbu: String
    + banco: String
    + titular_cuenta: String
}

class Efectivo {
}



Persona <|-- Cliente
Persona <|-- Proveedor

Material <|-- Plegados
Material <|-- CañoRedondo
Material <|-- CañoCuadrado
Material <|-- Chapa
Material <|-- Hierro
Material <|-- Angulo
Material <|-- Planchuela
Material <|-- Perfil

Material "0..*" -- "0..1" Proveedor : es_provisto

Cliente "1" --O "0..*" Trabajo : tiene
Trabajo "1" o-- "0..*" Material : utiliza

Cliente "1" -- "0..*" Entrega : recibe
Proveedor "1" -- "0..*" Entrega : entrega
Entrega "1" -- "0..*" Material : contiene

Cliente "1" -- "0..*" Pago : realiza
Pago <|-- Efectivo
Pago <|-- Transferencia

@enduml